#pragma once
// GENERATED by tools/gen_dictionary.py from spec/FIX44.xml — do not edit.
#include "fix/groups.hpp"

namespace fix::fix44 {

inline constexpr int kMembers_33[] = {58, 354, 355};
inline constexpr int kDelims_33[] = {58};
inline constexpr int kMembers_73[] = {1, 6, 11, 12, 13, 14, 15, 18, 21, 22, 23, 37, 38, 39, 40, 44, 48, 54, 55, 58, 59, 60, 63, 64, 65, 66, 67, 70, 75, 77, 78, 81, 84, 99, 100, 103, 106, 107, 110, 111, 114, 117, 120, 121, 126, 140, 151, 152, 160, 167, 168, 192, 193, 198, 200, 201, 202, 203, 206, 207, 210, 211, 218, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 231, 232, 235, 236, 239, 240, 255, 348, 349, 350, 351, 354, 355, 376, 377, 386, 388, 389, 401, 423, 427, 432, 453, 454, 460, 461, 468, 469, 470, 471, 472, 479, 494, 497, 516, 526, 528, 529, 541, 543, 544, 581, 582, 583, 589, 590, 591, 635, 636, 640, 660, 662, 663, 667, 691, 696, 697, 698, 699, 701, 711, 756, 761, 762, 775, 799, 800, 835, 836, 837, 838, 840, 841, 842, 843, 844, 846, 847, 848, 849, 854, 864, 873, 874, 875, 876, 947};
inline constexpr int kDelims_73[] = {11};
inline constexpr int kMembers_78[] = {12, 13, 79, 80, 81, 85, 119, 120, 136, 153, 154, 155, 156, 161, 169, 170, 171, 172, 208, 209, 360, 361, 366, 467, 479, 497, 539, 573, 576, 661, 736, 737, 741, 742, 756, 776, 780, 948};
inline constexpr int kDelims_78[] = {79};
inline constexpr int kMembers_85[] = {165, 781, 787};
inline constexpr int kDelims_85[] = {165};
inline constexpr int kMembers_124[] = {17, 29, 31, 32, 527, 669};
inline constexpr int kDelims_124[] = {17, 32};
inline constexpr int kMembers_136[] = {137, 138, 139, 891};
inline constexpr int kDelims_136[] = {137};
inline constexpr int kMembers_146[] = {1, 15, 22, 38, 40, 44, 48, 54, 55, 58, 60, 62, 63, 64, 65, 106, 107, 126, 140, 152, 167, 192, 193, 200, 201, 202, 206, 207, 218, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 231, 232, 235, 236, 239, 240, 255, 303, 336, 348, 349, 350, 351, 354, 355, 423, 453, 454, 460, 461, 468, 469, 470, 471, 472, 516, 537, 541, 543, 555, 561, 562, 581, 625, 640, 660, 662, 663, 667, 668, 691, 692, 696, 697, 698, 699, 701, 711, 735, 761, 762, 788, 827, 854, 864, 869, 870, 873, 874, 875, 876, 898, 913, 914, 915, 916, 917, 918, 919, 947};
inline constexpr int kDelims_146[] = {55};
inline constexpr int kMembers_199[] = {104};
inline constexpr int kDelims_199[] = {104};
inline constexpr int kMembers_215[] = {216, 217};
inline constexpr int kDelims_215[] = {216};
inline constexpr int kMembers_232[] = {233, 234};
inline constexpr int kDelims_232[] = {233};
inline constexpr int kMembers_267[] = {269};
inline constexpr int kDelims_267[] = {269};
inline constexpr int kMembers_268[] = {15, 18, 22, 37, 48, 55, 58, 59, 65, 106, 107, 110, 126, 167, 200, 201, 202, 206, 207, 223, 224, 225, 226, 227, 228, 231, 239, 240, 255, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 299, 336, 346, 348, 349, 350, 351, 354, 355, 432, 451, 454, 460, 461, 470, 471, 472, 541, 543, 546, 555, 625, 667, 691, 711, 762, 811, 864, 873, 874, 875, 876, 947};
inline constexpr int kDelims_268[] = {269, 279};
inline constexpr int kMembers_295[] = {15, 22, 40, 48, 55, 60, 62, 64, 65, 106, 107, 132, 133, 134, 135, 167, 188, 189, 190, 191, 192, 193, 200, 201, 202, 206, 207, 223, 224, 225, 226, 227, 228, 231, 239, 240, 255, 299, 336, 348, 349, 350, 351, 368, 454, 460, 461, 470, 471, 472, 541, 543, 555, 625, 631, 632, 633, 634, 642, 643, 667, 691, 711, 762, 788, 864, 873, 874, 875, 876, 898, 913, 914, 915, 916, 917, 918, 919, 947};
inline constexpr int kDelims_295[] = {55, 299};
inline constexpr int kMembers_296[] = {241, 242, 243, 244, 245, 246, 247, 256, 295, 302, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 315, 316, 317, 318, 362, 363, 364, 365, 367, 435, 436, 457, 462, 463, 542, 592, 593, 594, 595, 763, 810, 877, 878, 879, 882, 883, 884, 885, 886, 887, 893, 941};
inline constexpr int kDelims_296[] = {302};
inline constexpr int kMembers_382[] = {337, 375, 437, 438, 655};
inline constexpr int kDelims_382[] = {375};
inline constexpr int kMembers_386[] = {336, 625};
inline constexpr int kDelims_386[] = {336};
inline constexpr int kMembers_398[] = {399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 441};
inline constexpr int kDelims_398[] = {399};
inline constexpr int kMembers_420[] = {1, 12, 13, 44, 54, 58, 63, 64, 66, 336, 354, 355, 406, 421, 423, 430, 479, 497, 625, 660};
inline constexpr int kDelims_420[] = {12, 66};
inline constexpr int kMembers_428[] = {22, 48, 55, 65, 106, 107, 167, 200, 201, 202, 206, 207, 223, 224, 225, 226, 227, 228, 231, 239, 240, 255, 348, 349, 350, 351, 454, 460, 461, 470, 471, 472, 541, 543, 667, 691, 762, 864, 873, 874, 875, 876, 947};
inline constexpr int kDelims_428[] = {55};
inline constexpr int kMembers_453[] = {447, 448, 452, 802};
inline constexpr int kDelims_453[] = {448};
inline constexpr int kMembers_454[] = {455, 456};
inline constexpr int kDelims_454[] = {455};
inline constexpr int kMembers_457[] = {458, 459};
inline constexpr int kDelims_457[] = {458};
inline constexpr int kMembers_473[] = {474, 475, 482, 486, 509, 511, 522, 539};
inline constexpr int kDelims_473[] = {509};
inline constexpr int kMembers_510[] = {477, 478, 498, 499, 500, 501, 502, 512};
inline constexpr int kDelims_510[] = {477};
inline constexpr int kMembers_518[] = {519, 520, 521};
inline constexpr int kDelims_518[] = {519};
inline constexpr int kMembers_534[] = {41, 535, 536};
inline constexpr int kDelims_534[] = {41};
inline constexpr int kMembers_539[] = {524, 525, 538, 804};
inline constexpr int kDelims_539[] = {524};
inline constexpr int kMembers_552[] = {1, 11, 12, 13, 15, 18, 37, 38, 40, 41, 54, 58, 66, 70, 75, 77, 78, 81, 118, 119, 120, 121, 136, 152, 155, 156, 157, 158, 159, 198, 203, 229, 230, 232, 237, 238, 336, 354, 355, 376, 377, 381, 453, 468, 469, 479, 483, 497, 516, 518, 526, 528, 529, 544, 575, 576, 578, 579, 581, 582, 583, 586, 589, 590, 591, 625, 635, 659, 660, 738, 752, 775, 821, 825, 826, 854, 920, 921, 922, 943};
inline constexpr int kDelims_552[] = {54};
inline constexpr int kMembers_555[] = {248, 249, 250, 251, 252, 253, 254, 257, 539, 556, 564, 565, 566, 587, 588, 596, 597, 598, 599, 600, 601, 602, 603, 604, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 637, 654, 670, 676, 677, 678, 679, 680, 681, 682, 683, 684, 686, 687, 690, 739, 740, 764, 942, 955, 956};
inline constexpr int kDelims_555[] = {600};
inline constexpr int kMembers_558[] = {167, 460, 461, 762};
inline constexpr int kDelims_558[] = {167};
inline constexpr int kMembers_576[] = {577};
inline constexpr int kDelims_576[] = {577};
inline constexpr int kMembers_580[] = {60, 75};
inline constexpr int kDelims_580[] = {75};
inline constexpr int kMembers_604[] = {605, 606};
inline constexpr int kDelims_604[] = {605};
inline constexpr int kMembers_627[] = {628, 629, 630};
inline constexpr int kDelims_627[] = {628};
inline constexpr int kMembers_670[] = {671, 672, 673, 674, 675, 756};
inline constexpr int kDelims_670[] = {671};
inline constexpr int kMembers_683[] = {688, 689};
inline constexpr int kDelims_683[] = {688};
inline constexpr int kMembers_702[] = {539, 703, 704, 705, 706};
inline constexpr int kDelims_702[] = {703};
inline constexpr int kMembers_711[] = {11, 15, 44, 54, 58, 140, 241, 242, 243, 244, 245, 246, 247, 256, 305, 306, 307, 308, 309, 310, 311, 312, 313, 315, 316, 317, 318, 354, 355, 362, 363, 364, 365, 435, 436, 457, 462, 463, 526, 542, 592, 593, 594, 595, 732, 733, 763, 810, 877, 878, 879, 882, 883, 884, 885, 886, 887, 941, 944};
inline constexpr int kDelims_711[] = {311};
inline constexpr int kMembers_735[] = {695};
inline constexpr int kDelims_735[] = {695};
inline constexpr int kMembers_753[] = {707, 708};
inline constexpr int kDelims_753[] = {707};
inline constexpr int kMembers_756[] = {757, 758, 759, 806};
inline constexpr int kDelims_756[] = {757};
inline constexpr int kMembers_768[] = {769, 770, 771};
inline constexpr int kDelims_768[] = {769};
inline constexpr int kMembers_778[] = {54, 85, 126, 162, 163, 167, 168, 169, 170, 171, 172, 214, 453, 460, 461, 476, 488, 489, 490, 491, 492, 503, 504, 505, 779};
inline constexpr int kDelims_778[] = {162};
inline constexpr int kMembers_781[] = {782, 783, 784, 801};
inline constexpr int kDelims_781[] = {782};
inline constexpr int kMembers_801[] = {785, 786};
inline constexpr int kDelims_801[] = {785};
inline constexpr int kMembers_802[] = {523, 803};
inline constexpr int kDelims_802[] = {523};
inline constexpr int kMembers_804[] = {545, 805};
inline constexpr int kDelims_804[] = {545};
inline constexpr int kMembers_806[] = {760, 807};
inline constexpr int kDelims_806[] = {760};
inline constexpr int kMembers_816[] = {817};
inline constexpr int kDelims_816[] = {817};
inline constexpr int kMembers_862[] = {528, 529, 863};
inline constexpr int kDelims_862[] = {528};
inline constexpr int kMembers_864[] = {865, 866, 867, 868};
inline constexpr int kDelims_864[] = {865};
inline constexpr int kMembers_870[] = {871, 872};
inline constexpr int kDelims_870[] = {871};
inline constexpr int kMembers_887[] = {888, 889};
inline constexpr int kDelims_887[] = {888};
inline constexpr int kMembers_897[] = {571, 818};
inline constexpr int kDelims_897[] = {571};
inline constexpr int kMembers_936[] = {283, 284, 928, 929, 930, 931};
inline constexpr int kDelims_936[] = {930};
inline constexpr int kMembers_938[] = {896};
inline constexpr int kDelims_938[] = {896};
inline constexpr int kMembers_948[] = {949, 950, 951, 952};
inline constexpr int kDelims_948[] = {949};
inline constexpr int kMembers_952[] = {953, 954};
inline constexpr int kDelims_952[] = {953};

inline constexpr GroupDef kGroups[] = {
    {33, kDelims_33, 1, kMembers_33, 3},
    {73, kDelims_73, 1, kMembers_73, 160},
    {78, kDelims_78, 1, kMembers_78, 38},
    {85, kDelims_85, 1, kMembers_85, 3},
    {124, kDelims_124, 2, kMembers_124, 6},
    {136, kDelims_136, 1, kMembers_136, 4},
    {146, kDelims_146, 1, kMembers_146, 109},
    {199, kDelims_199, 1, kMembers_199, 1},
    {215, kDelims_215, 1, kMembers_215, 2},
    {232, kDelims_232, 1, kMembers_232, 2},
    {267, kDelims_267, 1, kMembers_267, 1},
    {268, kDelims_268, 2, kMembers_268, 85},
    {295, kDelims_295, 2, kMembers_295, 79},
    {296, kDelims_296, 1, kMembers_296, 52},
    {382, kDelims_382, 1, kMembers_382, 5},
    {386, kDelims_386, 1, kMembers_386, 2},
    {398, kDelims_398, 1, kMembers_398, 11},
    {420, kDelims_420, 2, kMembers_420, 20},
    {428, kDelims_428, 1, kMembers_428, 43},
    {453, kDelims_453, 1, kMembers_453, 4},
    {454, kDelims_454, 1, kMembers_454, 2},
    {457, kDelims_457, 1, kMembers_457, 2},
    {473, kDelims_473, 1, kMembers_473, 8},
    {510, kDelims_510, 1, kMembers_510, 8},
    {518, kDelims_518, 1, kMembers_518, 3},
    {534, kDelims_534, 1, kMembers_534, 3},
    {539, kDelims_539, 1, kMembers_539, 4},
    {552, kDelims_552, 1, kMembers_552, 80},
    {555, kDelims_555, 1, kMembers_555, 63},
    {558, kDelims_558, 1, kMembers_558, 4},
    {576, kDelims_576, 1, kMembers_576, 1},
    {580, kDelims_580, 1, kMembers_580, 2},
    {604, kDelims_604, 1, kMembers_604, 2},
    {627, kDelims_627, 1, kMembers_627, 3},
    {670, kDelims_670, 1, kMembers_670, 6},
    {683, kDelims_683, 1, kMembers_683, 2},
    {702, kDelims_702, 1, kMembers_702, 5},
    {711, kDelims_711, 1, kMembers_711, 59},
    {735, kDelims_735, 1, kMembers_735, 1},
    {753, kDelims_753, 1, kMembers_753, 2},
    {756, kDelims_756, 1, kMembers_756, 4},
    {768, kDelims_768, 1, kMembers_768, 3},
    {778, kDelims_778, 1, kMembers_778, 25},
    {781, kDelims_781, 1, kMembers_781, 4},
    {801, kDelims_801, 1, kMembers_801, 2},
    {802, kDelims_802, 1, kMembers_802, 2},
    {804, kDelims_804, 1, kMembers_804, 2},
    {806, kDelims_806, 1, kMembers_806, 2},
    {816, kDelims_816, 1, kMembers_816, 1},
    {862, kDelims_862, 1, kMembers_862, 3},
    {864, kDelims_864, 1, kMembers_864, 4},
    {870, kDelims_870, 1, kMembers_870, 2},
    {887, kDelims_887, 1, kMembers_887, 2},
    {897, kDelims_897, 1, kMembers_897, 2},
    {936, kDelims_936, 1, kMembers_936, 6},
    {938, kDelims_938, 1, kMembers_938, 1},
    {948, kDelims_948, 1, kMembers_948, 4},
    {952, kDelims_952, 1, kMembers_952, 2},
};

inline constexpr Dictionary kDictionary{kGroups, sizeof(kGroups) / sizeof(kGroups[0])};

} // namespace fix::fix44
