#!/usr/bin/env python3
"""Generate include/fix/dictionary_fix44.hpp from a QuickFIX-format FIX XML spec.

Emits a constexpr table of repeating-group definitions: for every <group>
in the spec (message bodies, header, trailer, and components, recursively),
the count tag, the set of delimiter tags (first field of the group in each message that uses it), and the full
set of member tags — including the count tags of nested groups.

Usage: tools/gen_dictionary.py spec/FIX44.xml > include/fix/dictionary_fix44.hpp
"""
import sys
import xml.etree.ElementTree as ET

def main(path):
    root = ET.parse(path).getroot()
    fields = {f.get('name'): int(f.get('number')) for f in root.find('fields')}
    components = {c.get('name'): c for c in root.find('components')}

    groups = {}  # count_tag -> (delimiter_tag, sorted member tags)

    def first_tag(node):
        """Delimiter tag: first leaf field of the group, descending into components."""
        for ch in node:
            if ch.tag == 'field':
                return fields[ch.get('name')]
            if ch.tag == 'group':
                return fields[ch.get('name')]
            if ch.tag == 'component':
                t = first_tag(components[ch.get('name')])
                if t is not None:
                    return t
        return None

    def members(node, acc):
        for ch in node:
            if ch.tag == 'field':
                acc.add(fields[ch.get('name')])
            elif ch.tag == 'group':
                acc.add(fields[ch.get('name')])   # nested count tag is a member
                walk(ch)
            elif ch.tag == 'component':
                members(components[ch.get('name')], acc)
        return acc

    def walk(node):
        for ch in node:
            if ch.tag == 'group':
                ct = fields[ch.get('name')]
                delim = first_tag(ch)
                mem = members(ch, set())
                if ct in groups:
                    # Same count tag reused across messages (e.g. NoMDEntries is
                    # delimited by 269 in W and 279 in X): union both sets.
                    d0, m0 = groups[ct]
                    groups[ct] = (d0 | {delim}, m0 | mem)
                else:
                    groups[ct] = ({delim}, mem)
            elif ch.tag == 'component':
                walk(components[ch.get('name')])

    for sect in ('header', 'trailer', 'messages'):
        walk(root.find(sect))
    for comp in components.values():
        walk(comp)

    out = sys.stdout
    out.write('#pragma once\n')
    out.write('// GENERATED by tools/gen_dictionary.py from %s — do not edit.\n' % path)
    out.write('#include "fix/groups.hpp"\n\nnamespace fix::fix44 {\n\n')
    all_members = []
    for ct in sorted(groups):
        delim, mem = groups[ct]
        arr = sorted(mem)
        out.write('inline constexpr int kMembers_%d[] = {%s};\n' % (ct, ', '.join(map(str, arr))))
        out.write('inline constexpr int kDelims_%d[] = {%s};\n' % (ct, ', '.join(map(str, sorted(delim)))))
    out.write('\ninline constexpr GroupDef kGroups[] = {\n')
    for ct in sorted(groups):
        delim, mem = groups[ct]
        out.write('    {%d, kDelims_%d, %d, kMembers_%d, %d},\n' % (ct, ct, len(delim), ct, len(mem)))
    out.write('};\n\n')
    out.write('inline constexpr Dictionary kDictionary{kGroups, sizeof(kGroups) / sizeof(kGroups[0])};\n\n')
    out.write('} // namespace fix::fix44\n')

if __name__ == '__main__':
    main(sys.argv[1])
